language: java
jdk:
  - openjdk7
  - oraclejdk8
script: for mod in cadc-adql  cadc-tap-server  cadc-tap-schema  cadc-test-tap  example-tap; do cd $mod; gradle --full-stacktrace build javadoc install || break -1; cd ..; done 

